# Generated by Django 3.0.6 on 2020-08-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0002_auto_20200808_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='iimage',
            name='aimage',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
