# Generated by Django 3.1 on 2020-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0005_auto_20200808_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='iimage',
            name='bimage',
            field=models.ImageField(default='default.jpg', upload_to='photos'),
        ),
    ]
