# Generated by Django 3.1 on 2020-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0007_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='aimage',
            field=models.ImageField(default='default.jpg', upload_to='photos'),
        ),
    ]
