# Generated by Django 3.1 on 2020-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0008_task_aimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
