# Generated by Django 3.1 on 2020-08-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0009_auto_20200813_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iimage',
            name='thumbnailUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='iimage',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
