# Generated by Django 3.1 on 2020-08-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0013_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='latitude',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
