# Generated by Django 3.1 on 2020-08-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0014_auto_20200815_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='latitude',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='longitude',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
