# Generated by Django 3.1 on 2020-08-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0015_auto_20200815_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=4000),
        ),
    ]
