# Generated by Django 3.1 on 2020-08-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactapp', '0016_auto_20200817_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment1', models.CharField(blank=True, default='Bkash', max_length=300, null=True)),
                ('payment2', models.CharField(blank=True, default='Nagad', max_length=300, null=True)),
                ('payment3', models.CharField(blank=True, default='Rocket', max_length=300, null=True)),
                ('payment4', models.CharField(blank=True, default='Bank1', max_length=300, null=True)),
                ('payment5', models.CharField(blank=True, default='Bank2', max_length=300, null=True)),
                ('payment6', models.CharField(blank=True, default='Bank3', max_length=300, null=True)),
                ('payment7', models.CharField(blank=True, default='Bank4', max_length=300, null=True)),
                ('payment8', models.CharField(blank=True, default='others', max_length=300, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reactapp.album')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other1', models.CharField(blank=True, default='some', max_length=100, null=True)),
                ('other2', models.CharField(blank=True, default='some', max_length=100, null=True)),
                ('other3', models.CharField(blank=True, default='some', max_length=100, null=True)),
                ('other4', models.CharField(blank=True, default='some', max_length=100, null=True)),
                ('other5', models.CharField(blank=True, default='some', max_length=100, null=True)),
                ('other6', models.CharField(blank=True, default='some', max_length=100, null=True)),
                ('other7', models.CharField(blank=True, default='some', max_length=100, null=True)),
                ('other8', models.CharField(blank=True, default='some', max_length=100, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='reactapp.album')),
            ],
        ),
    ]
